completed_stages = ["fit_score", "fit_phi_sigma", "estimate_residuals"]
created_at = "2026-04-03T12:41:00"
run_dir = "/home/ludogio/Documents/JuliaProjects/GiulioProjects/ScoreEstimation.jl/scripts/coupled_l63/runs/run_004"
config_path = "/home/ludogio/Documents/JuliaProjects/GiulioProjects/ScoreEstimation.jl/scripts/coupled_l63/parameters.toml"
run_id = 4
run_name = "run_004"

[artifacts.low_resolution_dataset]
sample_dt = 11.8
cache_hit = true
n_samples = 1000000
hash = "7e94224286a44110b660fcc26eb69d6f8626af00"
path = "/home/ludogio/Documents/JuliaProjects/GiulioProjects/ScoreEstimation.jl/scripts/coupled_l63/data/datasets/low_res/7e94224286a44110b660fcc26eb69d6f8626af00/dataset.h5"

[artifacts.phi_sigma]
cache_hit = false
hash = "d280a1c1e57e52a6cdb13ac32942e5d826472aea"
objective = 3.9723901130214143
clusters = 9210
use_identity_sigma = false
summary_path = "/home/ludogio/Documents/JuliaProjects/GiulioProjects/ScoreEstimation.jl/scripts/coupled_l63/data/phi_sigma/d280a1c1e57e52a6cdb13ac32942e5d826472aea/phi_sigma_summary.toml"
path = "/home/ludogio/Documents/JuliaProjects/GiulioProjects/ScoreEstimation.jl/scripts/coupled_l63/data/phi_sigma/d280a1c1e57e52a6cdb13ac32942e5d826472aea/phi_sigma.h5"
use_identity_phi = false

[artifacts.score]
cache_hit = false
selected_noise_scale = 0.02
hash = "4e709a0ce634284a72e8e5d4e5600fdbc26dd435"
training_figure_png = "/home/ludogio/Documents/JuliaProjects/GiulioProjects/ScoreEstimation.jl/scripts/coupled_l63/runs/run_004/score/score_training_diagnostics.png"
training_figure_pdf = "/home/ludogio/Documents/JuliaProjects/GiulioProjects/ScoreEstimation.jl/scripts/coupled_l63/runs/run_004/score/score_training_diagnostics.pdf"
score_objective = 3.0863071066071033
summary_path = "/home/ludogio/Documents/JuliaProjects/GiulioProjects/ScoreEstimation.jl/scripts/coupled_l63/data/scores/4e709a0ce634284a72e8e5d4e5600fdbc26dd435/score_summary.toml"
path = "/home/ludogio/Documents/JuliaProjects/GiulioProjects/ScoreEstimation.jl/scripts/coupled_l63/data/scores/4e709a0ce634284a72e8e5d4e5600fdbc26dd435/score_model.bson"

[artifacts.residuals]
r2_rmse = 0.6246920885342376
r1_rmse = 0.5050796103491789
figure_png = "/home/ludogio/Documents/JuliaProjects/GiulioProjects/ScoreEstimation.jl/scripts/coupled_l63/runs/run_004/residuals/residual_validation.png"
source_phi_sigma_hash = "d280a1c1e57e52a6cdb13ac32942e5d826472aea"
figure_pdf = "/home/ludogio/Documents/JuliaProjects/GiulioProjects/ScoreEstimation.jl/scripts/coupled_l63/runs/run_004/residuals/residual_validation.pdf"

[artifacts.high_resolution_dataset]
sample_dt = 0.02
cache_hit = true
n_samples = 50000
hash = "6722a24235b96952ae7fbed1832c6660cfea28c5"
path = "/home/ludogio/Documents/JuliaProjects/GiulioProjects/ScoreEstimation.jl/scripts/coupled_l63/data/datasets/high_res/6722a24235b96952ae7fbed1832c6660cfea28c5/dataset.h5"
